version: "3.8"

services:
  nginx:
    container_name: nginx
    image: "eavedill_nginx"
    environment:
      - NGINX_PATH=$NGINX_PATH
      - WP_PATH=$WP_PATH
      - MARIADB_PATH=$MARIADB_PATH
    build:
      args:
        - NGINX_PATH=$NGINX_PATH
      context: $DOCKER_NGINX_PATH
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:$NGINX_PATH
    networks:
      - eavedill_inception
  wordpress:
    container_name: wordpress
    image: "eavedill_wordpress"
    environment:
      - WP_PATH=$WP_PATH
      - WP_TITLE=$WP_TITLE
      - WP_ADMIN_USER=$WP_ADMIN_USER
      - WP_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
      - WP_ADMIN_EMAIL=$WP_ADMIN_EMAIL
      - WP_USER=$WP_USER
      - WP_USER_PASSWORD=$WP_USER_PASSWORD
      - WP_USER_EMAIL=$WP_USER_EMAIL
      - WP_USER_ROLE=$WP_USER_ROLE
      - MARIADB_PATH=$MARIADB_PATH
      - MARIADB_NAME=$MARIADB_NAME
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_USER_PASSWORD=$MARIADB_USER_PASSWORD
      - MARIADB_HOST=$MARIADB_HOST
      - MARIADB_ROOT=$MARIADB_ROOT
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
      - DOMAIN_NAME=$DOMAIN_NAME
    build:
      args:
        - WP_PATH=$WP_PATH
#        - WP_ADMIN_USER=$WP_ADMIN_USER
      context: $DOCKER_WP_PATH
    ports:
      - 9000:9000
    volumes:
      - wordpress:$WP_PATH
    networks:
      - eavedill_inception
  mariadb:
    container_name: mariadb
    image: "eavedill_mariadb"
    environment:
      - MARIADB_PATH=$MARIADB_PATH
      - MARIADB_NAME=$MARIADB_NAME
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_USER_PASSWORD=$MARIADB_USER_PASSWORD
      - MARIADB_HOST=$MARIADB_HOST
      - MARIADB_ROOT=$MARIADB_ROOT
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
    build:
      args:
        - MARIADB_PATH=$MARIADB_PATH
      context: $DOCKER_MARIADB_PATH
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb:$MARIADB_PATH
    networks:
      - eavedill_inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: $HOME/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: $HOME/data/mariadb
      o: bind
      type: none 
networks:
  eavedill_inception:
    driver: bridge
    name: eavedill_inception
