services:
  nginx:
    container_name: nginx
    image: "eavedill_nginx"
    build:
      context: ./requirements/nginx/
      dockerfile: nginx.dockerfile
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:/usr/share/nginx/html
    depends_on: 
        - wordpress
    networks:
      - inception
  wordpress:
    container_name: wordpress
    image: "eavedill_wordpress"
    build:
      context: ./requirements/wordpress/
      dockerfile: wordpress.dockerfile
    restart: always
    ports:
      - 9000:9000
    environment:
      # DATABASE SETUP
      - MARIADB_DB_NAME=$MARIADB_DB_NAME
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_USER_PASSWORD=$MARIADB_USER_PASSWORD
      - MARIADB_HOST=$MARIADB_HOST
      # WORDPRESS BASIC CONFIGURATION
      - WP_PATH=$WP_PATH
      - WP_TITLE=$WP_TITLE
      - DOMAIN_NAME=$DOMAIN_NAME
      # ADMIN CREDENTIALS
      - WP_ADMIN_USER=$WP_ADMIN_USER
      - WP_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
      - WP_ADMIN_EMAIL=$WP_ADMIN_EMAIL
       # USER CREDENTIALS
      - WP_USER=$WP_USER
      - WP_USER_EMAIL=$WP_USER_EMAIL
      - WP_USER_ROLE=$WP_USER_ROLE
      - WP_USER_PASSWORD=$WP_USER_PASSWORD
    volumes:
      - wordpress:/srv/www/wordpress
    networks:
      - inception
  mariadb:
    container_name: mariadb
    image: "eavedill_mariadb"
    build:
      context: ./requirements/mariadb/
      dockerfile: mariadb.dockerfile
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: $HOME/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: $HOME/data/mariadb
      o: bind
      type: none 
networks:
  inception:
    driver: bridge
    name: eavedill_inception
