services:
  nginx:
    container_name: nginx
    image: "eavedill_nginx"
    build:
      context: $DOCKER_NGINX_PATH
      dockerfile: nginx.dockerfile
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:/usr/share/nginx/html
    depends_on: 
        - wordpress
    networks:
      - inception
  wordpress:
    container_name: wordpress
    image: "eavedill_wordpress"
    build:
      args:
        WP_PATH: $WP_PATH
      context: $DOCKER_WP_PATH
      dockerfile: wordpress.dockerfile
    restart: always
    ports:
      - 9000:9000
    volumes:
      - wordpress:$WP_PATH
    networks:
      - inception
  mariadb:
    container_name: mariadb
    image: "eavedill_mariadb"
    build:
      args:
        MARIADB_PATH: $MARIADB_PATH
      context: $DOCKER_MARIADB_PATH
      dockerfile: mariadb.dockerfile
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb:$MARIADB_PATH
    networks:
      - inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: $HOME/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: $HOME/data/mariadb
      o: bind
      type: none 
networks:
  inception:
    driver: bridge
    name: eavedill_inception
