
version: "3.0"
services:
  nginx:
    container_name: nginx
    image: "eavedill_nginx"
    build:
      context: ./nginx/
      dockerfile: nginx.dockerfile
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:/usr/share/nginx/html
        #    depends_on: 
        #- wordpress
  wordpress:
    container_name: wordpress
    image: "eavedill_wordpress"
    build:
      context: ./wordpress
      dockerfile: wordpress.dockerfile
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/wordpress
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/eavedill/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/eavedill/data/mariadb
      o: bind
      type: none 

