version: "1.0"
networks:
  inception:
    name: inception
services:
  nginx:
    image: nginx:42
    build:
      context: .
      dockerfile: nginx.dockerfile.env
    depends_on:
      - wordpress
    container_name: backend_srv
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/
      #- wordpress:/usr/share/nginx/html/
  wordpress:
    image: wordpress:42
    build:
      context: .
      dockerfile: wordpress.dockerfile.env
    container_name: wordpress_web
    depends_on:
      - mariadb
    ports:
      - 9000:80
    volumes:
      - wordpress:/var/www/html/
  mariadb:
    image: mariadb:42
    build:
      context: .
      dockerfile: mariadb.dockerfile.env
    container_name: mariadb_srv
    ports:
      - 3306:80
    environment:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ./web/
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ./web/database
      o: bind
      type: none      